### ISSUE TITLE
Can't run example simulation, gyro bias wrong size.

### ISSUE THREAD

**Issue by iandareid** [aau-cns/ABC-EqF#3]
When I run `python3 simulation.py data.csv ` I get the following output,

```
Loading dataset: data.csv

Traceback (most recent call last):
  File "/home/iandareid/repos/ABC-EqF/examples/simulation.py", line 273, in <module>
    sim(filter_args, data)
  File "/home/iandareid/repos/ABC-EqF/examples/simulation.py", line 195, in sim
    filter = EqF(*filter_args)
  File "/home/iandareid/repos/ABC-EqF/filter/EqF.py", line 70, in __init__
    self.__Dphi0 = stateActionDiff(self.__xi_0)             # Within equation 23
  File "/home/iandareid/repos/ABC-EqF/symmetry/symmetry.py", line 266, in stateActionDiff
    differential = numericalDifferential(coordsAction, np.zeros(((6 + 3 * len(xi.S)), 1)))
  File "/home/iandareid/repos/ABC-EqF/utils/utils.py", line 24, in numericalDifferential
    fx = f(x)
  File "/home/iandareid/repos/ABC-EqF/symmetry/symmetry.py", line 265, in <lambda>
    coordsAction = lambda U: local_coords(stateAction(G.exp(U), xi))
  File "/home/iandareid/repos/ABC-EqF/symmetry/symmetry.py", line 189, in stateAction
    return State(xi.R * X.A,
  File "/home/iandareid/repos/ABC-EqF/system/system.py", line 79, in __init__
    raise TypeError("The gyroscope bias has to be probvided as numpy array with shape (3, 1)")
TypeError: The gyroscope bias has to be probvided as numpy array with shape (3, 1) 
```

I am running Ubuntu 22.04 and the latest pylie.

From what I can tell, when the numerical differential is run on `stateAction`, it is not correctly shaping the bias, or perhaps inputting the state incorrectly. When I print the bias vector from the init function for State, the bias comes out as a 3x3 matrix of zeros.

I have tried rolling back commits to see if a previous commit works, they do not. I have also rolled back pylie to commits from the same period with no luck (specifically hash de363ef).

Is there something I am missing?

**Comment by iandareid** [comment]
Okay doing some digging, what is happening is that the expression on line [190](https://github.com/aau-cns/ABC-EqF/blob/c3ca29f255466e33cd7ce84f24cb8ce41618f179/symmetry/symmetry.py#L190) should be returning a (3,1) ndarray. However it is returning a 3x3 of zeros on the first call.

Specifically the line has,

`X.A.inv().as_matrix() @ (xi.b - SO3.vee(X.a))`

which on the first iteration, `X.A.inv().as_matrix()` evaluates to the 3x3 Identity matrix, and `(xi.b - SO3.vee(X.a))` evaluates to a 3x3 of zeros. Hence the product of the entire line is 3x3 of zeros.

`SO3.vee(X.a)` evaluates to a (3,) ndarray. In typical Numpy fashion it makes the subtraction from the bias an unexpected (at least to me) 3x3.

If I go  to the hash `2b2f8bda4a19cfbb0c00980a998a93b13a99f01f` for pylie and install numpy 1.26.2 I can get the code to run. So some change in pylie/numpy has caused the issue.

Now that it runs the example code, I think I will stop seeking the solution. Hopefully this helps someone.

**Comment by iandareid** [comment]
Additional note, the filter had some errors where it said that the name d was not defined. Looks like a class definition changed somewhere. So I used the commit c6573158ce82c1ee6948f377af6c101da5ddd786 of this repo and I now have no errors whatsoever.

**Comment by AlessandroFornasier** [comment]
Hi ian,

I do believe it is due to different package versions (numpy, pylie, etc.). I can have a look on Monday morning.

**Comment by AlessandroFornasier** [comment]
The overall issue was due to the latest updates in pylie rendering it not retrocompatible.

I have been able to reproduce the error and fix it. Please try the `fix/latest_pylie` branch and let me know.

For your convenience, I have also pushed a docker file to test it in an isolated environment. If you want to test the code in the docker container, follow the instructions on the readme, but remember to checkout `fix/latest_pylie` and pull from within the container.

Please let me know if this works for you so I can merge it back on main.
